services:
  mysql:
    image: mysql:8.0
    container_name: alumniportal-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: alumniportal
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - alumniportal-network

volumes:
  mysql_data:

networks:
  alumniportal-network:
    driver: bridge