services:
  app:
    image: ${{ DOCKER_USERNAME }}/unmsm-app:latest # Nombre de imagen consistente
    container_name: unmsm-backend
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "80:8080"
    environment:
      # Conexión a la DB (apunta al servicio 'mysql')
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/alumniportal?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      # AWS
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - AWS_S3_REGION=${AWS_S3_REGION}
      - CUSTOM_BUCKET_S3_NAME=${AWS_S3_BUCKET_NAME}
    restart: always
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: unmsm-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: alumniportal
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    # Configuración vital para reducir consumo de RAM en t3.micro
    command: --default-authentication-plugin=mysql_native_password --innodb-buffer-pool-size=256M
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge